spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/taskmanager
    username: taskmanager
    password: taskmanager
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
